### ISSUE TITLE
Snippet properties not updating

### ISSUE THREAD

**Issue by IIFLIPII** [wintercms/wn-pages-plugin#12]
- Winter CMS Build: 1.1.8
- Pages Plugin Version: 2.0.0
- PHP Version: 7.4.27

### Description:
When adding a snippet to a static page at first the html content gets rendered correctly. When changing the properties afterwards, the generated markup in the pages template file is updated, but the markup in the browser is still displaying the previous value.

Clearing caches isn't helping either.

### Steps To Reproduce:
- Create a snippet with at least one property and add it to a static page
- Load the page with the snippet.
- Change the property value of the snippet
- Reload the page -> the old value is still shown

**Comment by LukeTowers** [comment]
@IIFLIPII what was the solution to your problem?
