### ISSUE TITLE
Two snippets of the same type share the same values

### ISSUE THREAD

**Issue by IIFLIPII** [wintercms/wn-pages-plugin#13]
- Winter CMS Build: 1.1.8
- Pages Plugin Version: 2.0.0
- PHP Version: 7.4.27

### Description:
When adding two snippets of the same type, both will render with the same property values despite them having different values set.
Might be related to #12 

### Steps To Reproduce:
- Add two snippets of the same type to a static page but with different property values
- Load the page in the browser -> both snippets will share the property values of the first snippet

**Comment by IIFLIPII** [comment]
I did some further digging with the following results:

After a fresh installation of Winter CMS it worked for a while without any issues and then started happening again.

I think I narrowed it down to this function in the `Template` abstract class:

```php
public function render(array $context)
    {
        $level = ob_get_level();
        if ($this->env->isDebug()) {
            ob_start();
        } else {
            ob_start(function () { return ''; });
        }
        try {
            $this->display($context);
        } catch (\Throwable $e) {
            while (ob_get_level() > $level) {
                ob_end_clean();
            }

            throw $e;
        }

        return ob_get_clean();
    }
```

Initially the correct property values are stored inside the `$context` but as soon as the output buffering is turned on, it outputs the same value for every rendered template. So it seems to be connected to the cache somehow? I'm not too familiar with output buffering in PHP :/

**Comment by LukeTowers** [comment]
@IIFLIPII what was the solution to your problem?
