### ISSUE TITLE
Template not recognized

### ISSUE THREAD

**Issue by pierzo** [wintercms/wn-pages-plugin#16]
Hi, yesterday I have install fresh (web installer) wintercms. Add winter.pages plugin. To my template add  static page component as usual. Then on ma new static page I chose my template. But I get an error. 

ArgumentCountError: Too few arguments to function Twig\Environment::loadTemplate(), 1 passed in /usr/home/Eternia/domains/eternia.usermd.net/public_html/stan/plugins/winter/pages/classes/Controller.php on line 79 and at least 2 expected in /usr/home/Eternia/domains/eternia.usermd.net/public_html/stan/vendor/twig/twig/src/Environment.php:327

Same error as if I do not hook up template to static page. I so far try to chose another template / turn off plugins, same result, same error. 

Thanks!

**Comment by mjauvin** [comment]
how did you install winter.pages plugin?you must use latest version that resolves this problem.

**Comment by LukeTowers** [comment]
@mjauvin is correct, update to the latest version of the plugin by using composer.
