### ISSUE TITLE
Missing keywords field

### ISSUE THREAD

**Issue by oim37** [wintercms/wn-pages-plugin#25]
Hello,

In page settings i have 2 tabs, second include only 2 fields
(title) - this for page title
(meta title) - this for SEO title in browser
(meta description) - this SEO description

Where keywords field? How add this field to page settings tab.

**Comment by LukeTowers** [comment]
The `keywords` meta tag hasn't been relevant for over 13 years, see https://developers.google.com/search/blog/2009/09/google-does-not-use-keywords-meta-tag. 

Check out the [Winter.SEO](https://github.com/wintercms/wn-seo-plugin) plugin if you would like some enhanced SEO capabilities
