### ISSUE TITLE
How to show "Last Modified" date on frontend

### ISSUE THREAD

**Issue by oim37** [wintercms/wn-pages-plugin#39]
Hello,

![image](https://github.com/wintercms/wn-pages-plugin/assets/6842168/37ff5a78-998b-4164-80ec-be056f8eface)

help please, can't find how to show this data on frontend? Want to show this near title - this is very useful information - shows the relevance of the article.

Thank you very much in advance.

**Comment by bennothommo** [comment]
@oim37 the timestamp is accessible via `this.page.mtime` in Twig. You can do something like this in the Twig code to present it nicely:

```twig
Last updated on {{ this.page.mtime|date('l jS F, Y') }}
```

**Comment by oim37** [comment]
I'm very grateful, but he's unlike {{ this.page.title}} where it takes data from the page, it shows the modification date of the template file itself.

On all pages, today's date of editing the template file itself is displayed, and the date of editing the pages themselves is completely different.

**Comment by oim37** [comment]
I try {{page.mtime|date('l jS F, Y')}} and it workin good for static pages showing - Saturday 5th August, 2023

thanks for the help.

**Comment by oim37** [comment]
The only thing is that when switching languages, I have 5 of them, it always writes in English:

Saturday 5th August, 2023
Monday 13th February, 2023

**Comment by bennothommo** [comment]
Whoops, sorry, my bad! Good job on working out the right one! :)

I'm not sure how translations work with dates unfortunately. @mjauvin might be able to assist with this.

**Comment by mjauvin** [comment]
try:
```twig
{{ page.mtime | date('Y-m-d') }}
```

**Comment by oim37** [comment]
Yes, I did just that, just for interest, I searched (September) in winter files and find this path 
`domain.tld/modules/system/lang/ `
with complete translations.

`more domain.tld/modules/system/lang/de/client.php`
'months' => ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'],
or
`more domain.tld/modules/system/lang/ru/client.php`
'months' => ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],

That's me, simply, thank you!
