### ISSUE TITLE
How too add support for Hindi language

### ISSUE THREAD

**Issue by oim37** [wintercms/wn-pages-plugin#41]
- Winter CMS Build: 1.2.5
- Pages Plugin Version: 2.1.2
- PHP Version: 8.3.6

### Description:
Html field in pages plugin not work correctly with hindi language.
It Blog plugin all same in main field.

### Steps To Reproduce:
![Hindi](https://github.com/wintercms/wn-pages-plugin/assets/6842168/d855245b-35ec-4d1d-9eab-67e13b304c26)

Text for sample 
```
<p class="hosting__text">किसी भी आवश्यकता के अनुरूप लचीली वर्चुअल होस्टिंग योजनाएँ। आपकी साइट के लिए उच्च गति और सुरक्षा के साथ व्यावसायिक होस्टिंग।</p>
<div class="hosting__table">
```

**Comment by LukeTowers** [comment]
Hmm, that's very odd. Might require updating Froala to fix it. Have you seen any similar error reports with Froala?

**Comment by oim37** [comment]
Apparently this is a feature of the language, since the dashes above the letters are a kind of addition and the cursor moves to the right.
