### ISSUE TITLE
Translated content not duplicated

### ISSUE THREAD

**Issue by steva82** [wintercms/wn-pages-plugin#43]
Winter CMS Build: 1.2.5
Pages Plugin Version: 2.1.3
PHP Version: 8.2.0
Translate 2.1.6 (first language EN, second language IT)

### Description:
When a Page with its translations is duplicated and saved, its translated content are not duplicated

### Steps To Reproduce:

1. create a page, translate its contents and save it
3. duplicate this page
4. edit its title, url and body in the original language
5. select the second language but there is nothing
<img width="1626" alt="img5" src="https://github.com/wintercms/wn-pages-plugin/assets/5539113/d7e52950-51c6-487e-b819-0911bf89a681">

Thanks.

**Comment by LukeTowers** [comment]
@der-On any ideas?

**Comment by der-On** [comment]
@LukeTowers will have a look.

**Comment by mjauvin** [comment]
@der-On when creating a static page with content for other locales, it creates the page in the `content/static-pages-[locale]` with that locale's content ... so that's most likely what doesn't get duplicated.
