### ISSUE TITLE
Unable to see static pages on frontend

### ISSUE THREAD

**Issue by mskraban** [wintercms/wn-pages-plugin#47]
- Winter CMS Build: Latest, just installed it
- Pages Plugin Version: 2.0.0
- PHP Version: 8.0

### Description:
Opening static page returns this error:
Too few arguments to function Twig\Environment::loadTemplate(), 1 passed in ... and at least 2 expected

![Error](https://i.imgur.com/O2sjMjP.png](https://i.imgur.com/O2sjMjP.png))

### Steps To Reproduce:
Create static page, visit it on frontend

**Comment by mjauvin** [comment]
update plugin to latest version

**Comment by mskraban** [comment]
2.0.0 is the version you get, when you download from plugin in the backend. Seems like 2.0.0 version is the latest version you can update here, even if you trigger force update.

It worker only via manual installation via composer. Now the version is 2.1.4

**Comment by LukeTowers** [comment]
@mskraban yes, we're working on fixing the backend updates functionality, please use composer at the moment.
