### ISSUE TITLE
Automatic generated slug not detected when saving new page

### ISSUE THREAD

**Issue by der-On** [wintercms/wn-pages-plugin#8]
- Winter CMS Build: 1.1.8 c15d216cc77f76fa0d50bc29fb098dae19a033e1
- Pages Plugin Version: 2.0.0
- PHP Version: 7.4

### Description:

When creating a new static page without manually entering an URL the URL generated from the entered title is not detected.

### Steps To Reproduce:

- I create a new static page
- I enter a title
- the slug get's automaticly generated
- I try to save the page
- A validation error shows up that the URL is required

**Comment by bennothommo** [comment]
@der-On I can't replicate this with the same details. There must be something else at play here.

Did you have multiple pages open? Did you save the page when perhaps you were already logged out? Anything else that might be able to help?

**Comment by der-On** [comment]
Indeed. I can confirm that I cannot reproduce it anymore. It actually happened on a coworkers machine. We will try to reproduce tomorrow. Will report back then.

**Comment by der-On** [comment]
Retried after an composer update to the latest 1.1.8 of winter and 2.0 of wn-pages-plugin and unable to reproduce.
Happily closing this now.
