### ISSUE TITLE
Froala Editor - Unlicensed copy of the Froala Editor. Use it legally by purchasing a license.

### ISSUE THREAD

**Issue by willouch** [wintercms/wn-pages-plugin#9]
- Winter CMS Build: Dev
- Pages Plugin Version: 2.0.0
- PHP Version: 8.0

### Description:
Unlicensed copy of the Froala Editor. Use it legally by purchasing a license.

**Comment by LukeTowers** [comment]
Where are you seeing that message? The Froala Editor used by Winter CMS is an older version that is licensed properly AFAIK.

**Comment by willouch** [comment]
Editing Static Pages

**Comment by bennothommo** [comment]
@willouch should be fixed by 592f43f514a13b1964753ef3e2748d7967a4a023. Let us know if you have any more issues.
